### PR TITLE
Version 2.0.0: Direct stream access + enable concurrent instances

### PR DESCRIPTION
**Pull request by point-source**
This is a significant API change but allows the user to directly access the PingData stream. It begins the ping when the stream is listened to and kills the process if the stream is closed/canceled. 

The stop() method is now an instance method rather than a class method and together with the instance stream, allows a user to create multiple simultaneous ping sessions and control them individually. This is helpful when you are scanning a range of IPs at once.

### CODE REVIEW

**Comment by zuvola** [comment]
Thank you for the great PR.
However, It seems that there is no summary output when ping is stopped with 'stop' method.

**Comment by point-source** [comment]
Oh good catch! I'll work on fixing that tomorrow. Thanks!

**Comment by point-source** [comment]
Alright, I fixed it for Android. Possibly fixed on iOS but also may not be due to a potential race condition. Not able to test the iOS side right now. Any chance you can take a look?

**Comment by zuvola** [comment]
It's perfect for Android.
iOS needs a little change, so I'll merge and fix it.
Thank you for your cooperation!

**Pull request merged**
